### ISSUE TITLE
grailsw vs. gradlew

### ISSUE THREAD

**Issue by mikemil** [grails-guides/rest-hibernate#6]
Just getting started going thru this document but I have seen some inconsistency between using ./grailsw and ./gradlew.   At first, when I tried this from Starbucks - it seemed like it hung.   I tried when I got home and I think the grailsw was using gradle version 3.2 and the gradlew package using gradle 3.0.   As a result, after just  couple steps into the doc, I had to download two different versions of Gradle.

**Comment by niravassar** [comment]
gradlew is a wrapper that will download the version of gradlew specified in the gradle-wrapper.properties file. The intent if this is so that the script will download the appropriate version of gradle that is compatible with the grails application.
